#docker network create -d macvlan --subnet 192.168.128.0/24 --gateway 192.168.128.1 -o parent=wlo1 veth1 --aux-address "bridge=192.168.128.253"
#nmcli con add con-name macvlan-lan type macvlan ifname macvlan-lan ip4 192.168.128.253/32 dev wlo1 mode bridge
#nmcli con mod macvlan-lan +ipv4.routes "192.168.128.0/24"

version: "3.9"
services:

  blockchain-proj:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NAME=node1
    container_name: "node1"
    networks:
      - veth1
  node2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NAME=node2

    container_name: "node2"
    networks:
      - veth1

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:

      - NAME=node3

    container_name: "node3"
    networks:
      - veth1

  node4:
    build:
      context: .
      dockerfile: Dockerfile
    environment:

      - NAME=node4

    container_name: "node4"
    networks:
      - veth1

  node5:
    build:
      context: .
      dockerfile: Dockerfile
    environment:

      - NAME=node5

    container_name: "node5"
    networks:
      - veth1

  node6:
    build:
      context: .
      dockerfile: Dockerfile
    environment:

      - NAME=node6

    container_name: "node6"
    networks:
      - veth1

  node7:
    build:
      context: .
      dockerfile: Dockerfile
    environment:

      - NAME=node7

    container_name: "node7"
    networks:
      - veth1

  node8:
    build:
      context: .
      dockerfile: Dockerfile
    environment:

      - NAME=node8

    container_name: "node8"
    networks:
      - veth1

  node9:
    build:
      context: .
      dockerfile: Dockerfile
    environment:

      - NAME=node9

    container_name: "node9"
    networks:
      - veth1

  node10:
    build:
      context: .
      dockerfile: Dockerfile
    environment:

      - NAME=node10

    container_name: "node10"
    networks:
      - veth1

  node11:
    build:
      context: .
      dockerfile: Dockerfile
    environment:

      - NAME=node11

    container_name: "node11"
    networks:
      - veth1

  node12:
    build:
      context: .
      dockerfile: Dockerfile
    environment:

      - NAME=node12

    container_name: "node12"
    networks:
      - veth1

  node13:
    build:
      context: .
      dockerfile: Dockerfile
    environment:

      - NAME=node13

    container_name: "node13"
    networks:
      - veth1

  node14:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NAME=node14
    container_name: "node14"
    networks:
      - veth1

  node15:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NAME=node15
    container_name: "node15"
    networks:
      - veth1

  node16:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NAME=node16
    container_name: "node16"
    networks:
      - veth1

  node17:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NAME=node17
    container_name: "node17"
    networks:
      - veth1

  node18:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NAME=node18
    container_name: "node18"
    networks:
      - veth1

networks:
  veth1:
    external: true
