#docker network create -d macvlan --subnet 192.168.128.0/24 --gateway 192.168.128.1 -o parent=wlo1 veth1 --aux-address "bridge=192.168.128.253"
#nmcli con add con-name macvlan-lan type macvlan ifname macvlan-lan ip4 192.168.128.253/32 dev wlo1 mode bridge
#nmcli con mod macvlan-lan +ipv4.routes "192.168.128.0/24"

version: "3.9"
services:
  blockchain-proj:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 10
      labels:
        - "node.name=node-${TASK_SLOT}"
    environment:
      - NAME=${TASK_SLOT}
    networks:
      - veth1

networks:
  veth1:
    external: true
