version: "3.9"
services:

  blockchain-proj:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODES=10.6.7.3:9000,10.6.7.4:9000,10.6.7.5:9000,10.6.7.6:9000,10.6.7.7:9000,10.6.7.8:9000
      - NAME=node-1

    container_name: "node-1"
    networks:
      node-net:
        ipv4_address: 10.6.7.2
  node2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODES=10.6.7.4:9000,10.6.7.2:9000,10.6.7.5:9000,10.6.7.6:9000,10.6.7.7:9000,10.6.7.8:9000
      - NAME=node-2

    container_name: "node-2"
    networks:
      node-net:
        ipv4_address: 10.6.7.3
  node3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODES=10.6.7.3:9000,10.6.7.2:9000,10.6.7.5:9000,10.6.7.6:9000,10.6.7.7:9000,10.6.7.8:9000
      - NAME=node-3

    container_name: "node-3"
    networks:
      node-net:
        ipv4_address: 10.6.7.4
  node4:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODES=10.6.7.3:9000,10.6.7.2:9000,10.6.7.4:9000,10.6.7.6:9000,10.6.7.7:9000,10.6.7.8:9000
      - NAME=node-4

    container_name: "node-4"
    networks:
      node-net:
        ipv4_address: 10.6.7.5
  node5:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODES=10.6.7.3:9000,10.6.7.2:9000,10.6.7.4:9000,10.6.7.5:9000,10.6.7.7:9000,10.6.7.8:9000
      - NAME=node-5

    container_name: "node-5"
    networks:
      node-net:
        ipv4_address: 10.6.7.6
  node6:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODES=10.6.7.3:9000,10.6.7.2:9000,10.6.7.4:9000,10.6.7.5:9000,10.6.7.6:9000,10.6.7.8:9000
      - NAME=node-6

    container_name: "node-6"
    networks:
      node-net:
        ipv4_address: 10.6.7.7
  node7:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODES=10.6.7.3:9000,10.6.7.2:9000,10.6.7.4:9000,10.6.7.5:9000,10.6.7.6:9000,10.6.7.7:9000
      - NAME=node-7

    container_name: "node-7"
    networks:
      node-net:
        ipv4_address: 10.6.7.8




networks:
  node-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.7.0/24
          gateway: 10.6.7.1
